spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/users
#    url: jdbc:postgresql://localhost:4678/users
    username:
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    username:
    password:
    port: 587
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    debug: true