spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: 6441
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    username: niranjanthapa6441@gmail.com
    password: 9818_S@inik6441_22
    port: 587
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    debug: true